#!/usr/bin/env node
// Copies the web app's static data (apps/web/public/data, ~16MB, 349 JSON files)
// into apps/mobile/assets/data so it ships inside the APK as files.
//
// Why the odd extension: Metro inlines any require()d .json into the JS bundle
// (Phase 0 measured 26MB of Hermes bytecode that way). Renaming to .mvdata,
// which metro.config.js registers as an asset extension, makes each file a
// Metro *asset* instead: copied into the APK (android res/raw), resolved at
// runtime with expo-asset and read lazily with expo-file-system.
//
// Also writes assets/data/manifest.js: { "quran/2.json": require("./quran/2.mvdata"), … }
// keyed by the same data-root-relative paths core's loaders use. Everything
// under assets/data is generated and gitignored; re-run after `npm run build:data`.
import { mkdir, readdir, rm, copyFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(here, "../../web/public/data");
const dest = path.resolve(here, "../assets/data");

async function walk(dir, rel = "") {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const r = rel ? `${rel}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...(await walk(path.join(dir, entry.name), r)));
    else if (entry.name.endsWith(".json")) out.push(r);
  }
  return out;
}

try {
  await stat(src);
} catch {
  console.error(`sync-data: ${src} not found. Run \`npm run build:data\` at the repo root first.`);
  process.exit(1);
}

const files = (await walk(src)).sort((a, b) => a.localeCompare(b, "en", { numeric: true }));
await rm(dest, { recursive: true, force: true });

let bytes = 0;
const lines = [];
for (const rel of files) {
  const assetRel = rel.replace(/\.json$/, ".mvdata");
  const to = path.join(dest, assetRel);
  await mkdir(path.dirname(to), { recursive: true });
  await copyFile(path.join(src, rel), to);
  bytes += (await stat(to)).size;
  lines.push(`  ${JSON.stringify(rel)}: require(${JSON.stringify("./" + assetRel)}),`);
}

await writeFile(
  path.join(dest, "manifest.js"),
  "// GENERATED by scripts/sync-data.mjs: do not edit. Maps core data paths to Metro asset ids.\n" +
    "module.exports = {\n" + lines.join("\n") + "\n};\n",
);

console.log(`sync-data: ${files.length} files, ${(bytes / 1048576).toFixed(1)} MB -> ${path.relative(process.cwd(), dest) || dest}`);
